// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbS0ghu4a6zaNKQKyuCAgmkfSVCDl8tkU',
    appId: '1:189082212528:web:33c0e30ec8c74a0d4d4375',
    messagingSenderId: '189082212528',
    projectId: 'evently-2de42',
    authDomain: 'evently-2de42.firebaseapp.com',
    storageBucket: 'evently-2de42.firebasestorage.app',
    measurementId: 'G-4V0P5EMM2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA-j489_VEOBn-MT78pJWUHz0VxluShQQ',
    appId: '1:189082212528:android:5e6135549581ba234d4375',
    messagingSenderId: '189082212528',
    projectId: 'evently-2de42',
    storageBucket: 'evently-2de42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA0vZw9oeO6ieEUjuwflBRDNCiLoN2RTo',
    appId: '1:189082212528:ios:9b22fe2fb240b46b4d4375',
    messagingSenderId: '189082212528',
    projectId: 'evently-2de42',
    storageBucket: 'evently-2de42.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA0vZw9oeO6ieEUjuwflBRDNCiLoN2RTo',
    appId: '1:189082212528:ios:9b22fe2fb240b46b4d4375',
    messagingSenderId: '189082212528',
    projectId: 'evently-2de42',
    storageBucket: 'evently-2de42.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbS0ghu4a6zaNKQKyuCAgmkfSVCDl8tkU',
    appId: '1:189082212528:web:3cec03c5794acb014d4375',
    messagingSenderId: '189082212528',
    projectId: 'evently-2de42',
    authDomain: 'evently-2de42.firebaseapp.com',
    storageBucket: 'evently-2de42.firebasestorage.app',
    measurementId: 'G-F4KF1T1XWH',
  );
}
